# feed2h.cmake -DDLL=<built feed dll> -DH=<out header> : embed DLL bytes as C array
file(SIZE "${DLL}" len)
file(SHA256 "${DLL}" sum)
string(SUBSTRING "${sum}" 0 6 tag)
file(READ "${DLL}" data HEX)
string(REGEX REPLACE "(..)" "0x\\1," hex "${data}")
file(WRITE "${H}"
"/* generated by feed2h.cmake -- do not edit (endfield_feed.dll payload) */\n"
"static const unsigned char g_feedDll[] = {${hex}0x00};\n"
"static const unsigned int  g_feedDllLen = ${len}u;\n"
"static const char          g_feedDllTag[] = \"${tag}\";\n")
message(STATUS "feed2h: ${len} bytes -> ${H} (tag ${tag})")
